### ISSUE TITLE
Shown entered number Not match called number when enter more than10 digits on dialpad 

### ISSUE THREAD

**Issue by rehamalraee** [eopeter/flutter_dialpad#4]
I've entered more than 10 digits the dialer shows only 10 but when make the call it call with all entered digits

**Comment by eopeter** [comment]
Change your input mask to match your format.

**Comment by rehamalraee** [comment]
@eopeter I don't want to put any restriction on the view! because there is no expectation on what the user will enter

**Comment by rehamalraee** [comment]
Not Fixed !
