### ISSUE TITLE
Feature: Ability to Hide Subtitles

### ISSUE THREAD

**Issue by hardiklakhalani** [eopeter/flutter_dialpad#9]
The `subtitle ` is the name of the parameter which handles alphabets below the Numerics.

**Comment by eopeter** [comment]
will add this feature soon

**Comment by hardiklakhalani** [comment]
I tried it and forked repo worked in my project.
https://github.com/eopeter/flutter_dialpad/pull/10

**Comment by hardiklakhalani** [comment]
Made a PR, without messing up the previous formatting.
https://github.com/eopeter/flutter_dialpad/pull/11
